version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
    volumes:
      - react_build:/react/build
      
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/react
      - ./authentication/static:/static_web_auth
      - type: volume
        source: media_root
        target: /var/www/media
        read_only: true
    depends_on:
      - frontend
      - web-auth
      - web-quiz-editor
      - web-survey-editor

  db-auth:
    image: postgres
    volumes:
      - ./data-auth:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
     - "6432:5432"

  web-auth:
    build: 
      context: ./authentication
    command: bash initialize.sh
    volumes:
      - ./authentication:/code
    ports:
      - "8001:8000"
    depends_on:
      - db-auth

  db-quiz:
    image: postgres
    volumes:
      - ./data-quiz:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"

  web-quiz-editor:
    build: 
      context: ./quizmaker
    command: bash initialize.sh
    volumes:
      - ./quizmaker:/code
      - media_root:/mediafiles
    ports:
      - "8000:8000"
    depends_on:
      - db-quiz

  db-survey:
    image: postgres
    volumes:
      - ./data-survey:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "7432:5432"

  web-survey-editor:
    build: 
      context: ./surveymaker
    command: bash initialize.sh
    volumes:
      - ./surveymaker:/code
      - media_root:/mediafiles
    ports:
      - "8002:8000"
    depends_on:
      - db-survey

volumes:
  react_build:
  media_root:
