version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
    volumes:
      - react_build:/react/build
      
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/react
      - ./authentication/static:/static_web_auth
    depends_on:
      - frontend
      - web-auth
      - web-quiz-editor

  db-auth:
    image: postgres
    volumes:
      - ./data-auth:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
     - "6432:5432"

  web-auth:
    build:
      context: ./authentication
    command: bash initialize.sh
    volumes:
      - ./authentication:/code
    ports:
      - "8001:8000"
    depends_on:
      - db-auth

  db-quiz:
    image: postgres
    volumes:
      - ./data-quiz:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"

  web-quiz-editor:
    build:
      context: ./quizmaker
    command: gunicorn quizmaker.wsgi --bind 0.0.0.0:8000
    volumes:
      - ./quizmaker:/code
    ports:
      - "8000:8000"
    depends_on:
      - db-quiz

#  courses:
#    build:
#      context: ./courses
#      dockerfile: Dockerfile
#    ports:
#      - "8002:8000"
#    volumes:
#      - .:/code
#    depends_on:
#      - db-courses


  db-courses:
    image: postgres
    volumes:
      - ./data-course:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "7432:5432"


volumes:
  react_build:
