version: "3.9"

services:
  frontend:
    container_name: react-frontend
    build:
      context: ./frontend
    volumes:
      - react_build:/react/build
      
  nginx:
    image: nginx:latest
    ports:
      - "80:8080"
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/react
    depends_on:
      - frontend
      - web-auth

  db-auth:
    image: postgres
    container_name: db-auth
    volumes:
      - ./data-auth:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
     - "6432:5432"

  web-auth:
    build: 
      context: ./authentication
    container_name: web-auth
    command: gunicorn authentication.wsgi --bind 0.0.0.0:8000
    volumes:
      - ./authentication:/code
    ports:
      - "8001:8000"
    depends_on:
      - db-auth

  db-quiz:
    image: postgres
    container_name: db-quiz
    volumes:
      - ./data-quiz:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"

  web-quiz-editior:
    build: 
      context: ./quizmaker
    container_name: web-quiz-editor
    command: gunicorn quizmaker.wsgi --bind 0.0.0.0:8000
    volumes:
      - ./quizmaker:/code
    ports:
      - "8000:8000"
    depends_on:
      - db-quiz

volumes:
  react_build:
