# Generated by Django 4.2.7 on 2024-01-20 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nazwa')),
                ('topic', models.CharField(max_length=120, verbose_name='Temat')),
                ('author', models.PositiveIntegerField(null=True, verbose_name='Autor (ID)')),
                ('forum', models.PositiveIntegerField(default=None, null=True, verbose_name='Forum (ID)')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='import_surveys_files/')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('activated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('answers_type', models.CharField(choices=[('jednokrotny', 'jednokrotny'), ('wielokrotny', 'wielokrotny')], default='jednokrotny', max_length=11)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False, verbose_name='Status ankiety')),
                ('media', models.FileField(blank=True, null=True, upload_to='question_media/')),
                ('media_url', models.URLField(blank=True, null=True)),
                ('survey', models.ManyToManyField(related_name='questions', to='editor.survey')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('correct', models.BooleanField(default=False)),
                ('user_answer', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='editor.surveyquestion')),
            ],
        ),
    ]
