# Generated by Django 4.2.7 on 2024-01-15 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nazwa')),
                ('topic', models.CharField(max_length=120, verbose_name='Temat')),
                ('author', models.PositiveIntegerField(null=True, verbose_name='Autor (ID)')),
                ('number_of_questions', models.PositiveIntegerField(help_text='Liczba pytań w jednym podejściu', verbose_name='Liczba pytań')),
                ('max_time', models.IntegerField(default=1, help_text='Maksymalny czas trwania tesu [min]', verbose_name='Czas na rozwiązanie')),
                ('score_to_pass', models.PositiveIntegerField(help_text='Punkty wymagane do zaliczenia quizu [%]', verbose_name='Punkty wymagane do zaliczenia')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('difficulty', models.CharField(choices=[('łatwy', 'łatwy'), ('normalny', 'normalny'), ('trudny', 'trudny')], max_length=9, verbose_name='Poziom trudności')),
            ],
            options={
                'verbose_name_plural': 'Quizzes',
            },
        ),
        migrations.CreateModel(
            name='QuizFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='import_quizzes_files/')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('activated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('author', models.PositiveIntegerField(null=True, verbose_name='Autor (ID)')),
                ('answers_type', models.CharField(choices=[('jednokrotny', 'jednokrotny'), ('wielokrotny', 'wielokrotny')], default='jednokrotny', max_length=11)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('public', models.BooleanField(default=False)),
                ('media', models.FileField(blank=True, null=True, upload_to='question_media/')),
                ('media_url', models.URLField(blank=True, null=True)),
                ('quiz', models.ManyToManyField(related_name='questions', to='base.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.quizquestion')),
            ],
        ),
    ]
