# Generated by Django 4.2.7 on 2024-01-28 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.PositiveIntegerField(null=True)),
                ('score', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('quiz_pass', models.BooleanField(default=False)),
                ('quiz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.quiz')),
            ],
        ),
        migrations.RemoveField(
            model_name='quizanswer',
            name='question',
        ),
        migrations.DeleteModel(
            name='QuizFile',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='quiz',
        ),
        migrations.DeleteModel(
            name='QuizAnswer',
        ),
        migrations.DeleteModel(
            name='QuizQuestion',
        ),
    ]
