# Generated by Django 4.2.7 on 2024-01-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_quiz_forum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='quiz',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
