# Generated by Django 4.2.7 on 2024-01-01 21:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_alter_quiz_author_alter_quizquestion_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
