# Generated by Django 4.2.7 on 2024-01-01 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_quiz_created_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
