# Generated by Django 4.2.7 on 2024-01-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0004_quizquestion_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='question_media/'),
        ),
    ]
