# Generated by Django 4.2.7 on 2024-01-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0005_alter_quizquestion_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizquestion',
            old_name='image',
            new_name='media',
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='media_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
