# Generated by Django 4.2.7 on 2024-01-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0006_rename_image_quizquestion_media_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='media_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
