# Generated by Django 4.2.7 on 2024-01-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0008_delete_quizresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='forum',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name='Forum (ID)'),
        ),
    ]
