version: "3.9"

services:
  db-quiz:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
     - "5432:5432"
  web-quizmaker:
    build: quizmaker
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./quizmaker:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  db-auth:
    image: postgres
    volumes:
      - ./data-auth/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
     - "6432:5432"
  web-auth:
    build: auth
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./auth:/code
    ports:
      - "8001:8000"
    depends_on:
      - db-auth
