# Generated by Django 4.2.7 on 2024-01-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.PositiveIntegerField(null=True, verbose_name='Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='course',
            name='author',
            field=models.PositiveIntegerField(null=True, verbose_name='Autor (ID)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(max_length=100, verbose_name='Kategoria'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nazwa kursu'),
        ),
        migrations.AddField(
            model_name='class',
            name='attachments',
            field=models.ManyToManyField(to='course_manager.files', verbose_name='Zalaczniki'),
        ),
    ]
