# Generated by Django 4.2.7 on 2024-01-28 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_manager', '0002_delete_classroom_rename_author_course_owner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='course_id',
            new_name='k_course',
        ),
        migrations.RenameField(
            model_name='files',
            old_name='class_id',
            new_name='k_class',
        ),
        migrations.AddField(
            model_name='files',
            name='k_course',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='course_manager.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='owner',
            field=models.PositiveIntegerField(verbose_name='Autor (ID)'),
        ),
    ]
